[tool.ruff]
force-exclude = true
line-length = 120
output-format = "full"
target-version = "py310"  # Should match the minumum version in pyproject.toml
exclude = [
    ".git",
    ".svn",
    ".mypy_cache",
    ".mypy",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    ".coverage",
    "coverage",
    ".tox",
    ".idea",
    ".venv",
    "node_modules",
    "test_*.py",
    "tests_*.py",
]

[tool.ruff.lint]
select = [
    # flake8-builtins
    "A",
    # flake8-annotations
    "ANN",
    # Bugbear
    "B",
    # PYcodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # isort
    "I",
    # pep8-naming
    "N",
    # flake8-quotes
    "Q",
]
# Ignore codes such as "F401"
ignore = ["ANN101","ANN102"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
suppress-dummy-args = true

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
split-on-trailing-comma = false

[tool.ruff.lint.pep8-naming]
ignore-names = ["i","j","k","ex","_","pk","x","y","z","e","x1","x2","y1","y2","w","h","cx","cy","iou","k","v","f","ft"]

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = true
