# Visual and collision mesh parameters for tm12sx

visual_parameters:
  mesh_files:
    link_0:
      visual: package://tm_description/meshes/tm12s/visual/tm12s-tbb_a.obj
      collision: package://tm_description/meshes/tm12s/collision/tm12s-tbb_a_c.stl
    link_1:
      visual: package://tm_description/meshes/tm12s/visual/tm12s-j1-a.obj
      collision: package://tm_description/meshes/tm12s/collision/tm12s-j1-a_c.stl
    link_2:
      visual: package://tm_description/meshes/tm12s/visual/tm12s-a1.obj
      collision: package://tm_description/meshes/tm12s/collision/tm12s-a1_c.stl
    link_3:
      visual: package://tm_description/meshes/tm12s/visual/tm12s-a2.obj
      collision: package://tm_description/meshes/tm12s/collision/tm12s-a2_c.stl
    link_4:
      visual: package://tm_description/meshes/tm12s/visual/tm12s-j5.obj
      collision: package://tm_description/meshes/tm12s/collision/tm12s-j5_c.stl
    link_5:
      visual: package://tm_description/meshes/tm12s/visual/tm12s-j6.obj
      collision: package://tm_description/meshes/tm12s/collision/tm12s-j6_c.stl
    link_6:
      visual: package://tm_description/meshes/tm5s/visual/tm5s-iox.obj
      collision: package://tm_description/meshes/tm5s/collision/tm5s-iox_c.stl
